version: "3"
services:
  btc_runner:
    image: btc:latest
    build: .
    env_file:
      - default_compose.env
    environment:
      - RATE_BTC_DB=mysql://root:protectedByDocker0@mysql_runner/btc
      - RATE_BTC_AUTH=$${RATE_BTC_AUTH}
      - RATE_BTC_INTERVAL_UPDATE=$${RATE_BTC_INTERVAL_UPDATE}
      - RATE_BTC_PORT=80

  mysql_runner:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=protectedByDocker0

  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
